### ISSUE TITLE
Not working for CodeChef and SPOJ

### ISSUE THREAD

**Issue by manrajgrover** [koldbyte/CodeBackup#1] opened 2015-10-04 11:43 UTC
I tried using it on CodeChef and SPOJ. My username at both places is manrajsingh.

For CodeChef, it shows I have 87 AC solutions but doesn't fetch any code.
![codechef](https://cloud.githubusercontent.com/assets/5673050/10267676/f1319176-6aba-11e5-9749-8d0908eb0ca0.png)

For SPOJ, it shows this error.
![spoj](https://cloud.githubusercontent.com/assets/5673050/10267677/00f1a9e8-6abb-11e5-8d4b-11cf9260abd2.png)

Please confirm this issue or provide a solution. Thank you. 

PS. It is working for CodeForces.

**Comment by koldbyte** [comment] 2015-10-05 10:00
Confirming the issue. This is caused by the change in page structure(in case of codechef), and signedlist structure for spoj.
I will look into it.
Thanks for raising the issue.

**Comment by koldbyte** [comment] 2015-10-05 12:17
Identified the problems.
Codechef: Didn't handled the situation when there could be no submissions listed for a solved problem. (Yes, Codechef is now showing "No recent activity" for Practice problems in submission pages).

Spoj: Spoj now requires login to fetch the "signedlist" (the text list of all your submissions). 

I have updated the code and added a new release.

Try the latest release.

**Comment by manrajgrover** [comment] 2015-10-05 16:04
Thanks for quick reply.

CodeChef: It is working but throwing "Read timed out" after fetching few codes.

SPOJ: It is throwing "Read timed out" error even on logging in.

**Comment by koldbyte** [comment] 2015-10-06 03:16
It is most probably caused by slow internet connection (or slow website). 
You can retry multiple times till all the submissions have been downloaded.

**Comment by koldbyte** [comment] 2015-10-12 03:47
Closing the issue. I have self-tested it to be working. Please reply if its still not working.

**Closed as completed by koldbyte** 2015-10-12 03:47 UTC
